[inductor] fix blockptr advancement for broadcasted tensor (#175008)
Summary:

When calculating the advancement for blockptr within loopnest, we need to subtract the inner loop advancement. But it doesn't handle well the cases when a broadcasted tensor is used.

Say we have a broadcasted tensor from [M] => [M, N]. When the inner loop iterating over N, it doesn't need to advance the blockptr as the stride is 0. However, when it iterating over M, it tried to subtract the previous advancements with is none, causing a KeyError.

This diff fixes this by checking if the previous advancement ever exist.

```
  File "/re_cwd/buck-out/v2/gen/fbcode/2f9cba2a9291e016/caffe2/test/inductor/__torchinductor_strided_blocks__/torchinductor_strided_blocks#link-tree/torch/_inductor/codegen/triton.py", line 4992, in codegen_body
    prev_advancement = self.pointer_advancements[
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
torch._inductor.exc.InductorError: KeyError: 'block_ptr1'
```

Test Plan:
test_2d_reduction_with_broadcast

```
buck2 test "@//mode/opt" //caffe2/test/inductor:torchinductor_strided_blocks -- test_2d_reduction_with_broadcast_weights
```
before:
https://www.internalfb.com/buck2/fc809ac1-991a-4f2e-b1f2-62f6b3f30203
https://www.internalfb.com/intern/testinfra/testconsole/testrun/1688850210152099/

after:
https://www.internalfb.com/buck2/263181bf-b8f2-4abf-82c4-ea76063d26b5


```
triton_heuristics.reduction(
    size_hints={'x': 1, 'r0_': 64, 'r1_': 128},
    reduction_hint=ReductionHint.INNER,
    filename=__file__,
    triton_meta={'signature': {'in_ptr0': '*fp32', 'in_ptr1': '*fp32', 'out_ptr0': '*fp32', 'xnumel': 'constexpr', 'r0_numel': 'i32', 'r1_numel': 'i32', 'XBLOCK': 'constexpr', 'R0_BLOCK': 'constexpr', 'R1_BLOCK': 'constexpr'}, 'device': DeviceProperties(type='cuda', index=0, multi_processor_count=108, cc=80, major=8, regs_per_multiprocessor=65536, max_threads_per_multi_processor=2048, max_threads_per_block=1024, warp_size=32), 'constants': {'xnumel': 1}, 'native_matmul': False, 'enable_fp_fusion': True, 'launch_pdl': False, 'disable_ftz': False, 'configs': [{(0,): [['tt.divisibility', 16]], (1,): [['tt.divisibility', 16]], (2,): [['tt.divisibility', 16]], (4,): [['tt.divisibility', 16]], (5,): [['tt.divisibility', 16]]}]},
    inductor_meta={'grid_type': 'Grid1D', 'autotune_hints': set(), 'kernel_name': 'triton_red_fused_mul_sum_unsqueeze_0', 'mutated_arg_names': [], 'optimize_mem': True, 'no_x_dim': False, 'atomic_add_found': False, 'num_load': 2, 'num_store': 1, 'num_reduction': 1, 'backend_hash': '653D0FCD62DBAC5688A5D9FD4C23EE6BFFF4AD5DEB58938222C769B121A8BA1A', 'assert_indirect_indexing': True, 'autotune_local_cache': True, 'autotune_pointwise': True, 'autotune_remote_cache': None, 'force_disable_caches': False, 'dynamic_scale_rblock': True, 'max_autotune': False, 'max_autotune_pointwise': False, 'min_split_scan_rblock': 256, 'spill_threshold': 16, 'store_cubin': False, 'deterministic': False, 'force_filter_reduction_configs': False, 'are_deterministic_algorithms_enabled': False, 'is_fbcode': True}
)
triton.jit
def triton_red_fused_mul_sum_unsqueeze_0(in_ptr0, in_ptr1, out_ptr0, xnumel, r0_numel, r1_numel, XBLOCK : tl.constexpr, R0_BLOCK : tl.constexpr, R1_BLOCK : tl.constexpr):
    xnumel = 1
    r0_numel = 64
    r1_numel = 128
    rnumel = r0_numel * r1_numel
    RBLOCK: tl.constexpr = R0_BLOCK*R1_BLOCK
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:, None, None]
    xmask = tl.full([XBLOCK], True, tl.int1)[:, None, None]
    r0_base = tl.arange(0, R0_BLOCK)[None, :, None]
    r1_base = tl.arange(0, R1_BLOCK)[None, None, :]
    rbase = r1_base + r0_base*r1_numel
    block_ptr0 = tl.make_block_ptr(in_ptr0, shape=[64, 128], strides=[128, 1], block_shape=[R0_BLOCK, R1_BLOCK], order=[1, 0], offsets=[0, 0])
    block_ptr1 = tl.make_block_ptr(in_ptr1, shape=[64], strides=[1], block_shape=[R0_BLOCK], order=[0], offsets=[0])
    _tmp4 = tl.full([XBLOCK, R0_BLOCK, R1_BLOCK], 0, tl.float32)
    for r0_offset in tl.range(0, r0_numel, R0_BLOCK):
        r0_index = r0_offset + r0_base
        r0_mask = r0_index < r0_numel
        for r1_offset in tl.range(0, r1_numel, R1_BLOCK):
            r1_index = r1_offset + r1_base
            r1_mask = r1_index < r1_numel
            roffset = r1_offset + r0_offset*r1_numel
            rindex = r1_index + r0_index*r1_numel
            r0_0 = r0_index
            r1_1 = r1_index
            tmp0 = tl.load(block_ptr0, boundary_check=[0, 1], padding_option='zero', eviction_policy='evict_first')[None, :, :]
            tmp1 = tl.load(block_ptr1, boundary_check=[0], padding_option='zero', eviction_policy='evict_last')[None, :, None]
            tmp2 = tmp0 * tmp1
            tmp3 = tl.broadcast_to(tmp2, [XBLOCK, R0_BLOCK, R1_BLOCK])
            tmp5 = _tmp4 + tmp3
            _tmp4 = tl.where(r0_mask & r1_mask, tmp5, _tmp4)
            block_ptr0 = tl.advance(block_ptr0, [0, R1_BLOCK])
        block_ptr0 = tl.advance(block_ptr0, [R0_BLOCK, (-1)*R1_BLOCK*((127 + R1_BLOCK) // R1_BLOCK)])
        block_ptr1 = tl.advance(block_ptr1, [R0_BLOCK])
    tmp6 = tl.reshape(_tmp4, [XBLOCK, RBLOCK])
    tmp4 = tl.sum(tmp6, 1)[:, None, None]
    tl.store(out_ptr0 + (tl.full([1, 1, 1], 0, tl.int32).broadcast_to(XBLOCK, 1, R1_BLOCK)), tmp4, None)
''', device_str='cuda')
```

The resulted blockptr advancement here looks right.



also fixes:
```
FX_FBA_PASS_MANAGER_CONFIG=pm_config.yaml buck2 run @//mode/opt //mtia/host_runtime/repro:repro_afg_tools -- -a download -d ~/models/660701006 --snapshot "717786878_4693" --network merge --export
```
from D92109366 (for MTIA)

Reviewed By: blaine-rister

Differential Revision: D93272431