Prepare CUDA inputs only on CUDA device
In the `sample_input_scaled_mm_v2` function, some samples are generated only if
specific CUDA device capabilites are met. However, to check these capabilites
the following function is used: `torch.cuda.get_device_capability()`.
For non-CUDA based PyTorch builds, such as XPU, this will trigger the following
error: `AssertionError: Torch not compiled with CUDA enabled`.

This commit wraps the code for generating the capability-based input samples
into an if statement, which checks if the current device type is CUDA.