Avoid closing random file handles in Inductor
`CppCodeCache.load` returns a `ctypes.CDLL`.
That does not have a (Python class) `close` function so calling
`self.DLL.close()` calls whatever C function with name `close` happens
to exist. This is usually the glibc `close` that closes (file) handles.
As the argument is missing it closes whatever happens to be in the
register at that point.

In some tests this seems to close "fd=1", i.e. stdout. Sebsequent
writes/print then fails with
> OSError: [Errno 9] Bad file descriptor

Simply remove the `close` call for now.